[project]
name = "nlpvise"
version = "1.0.0"
description = "This project is completed as a part of final project for CSE6250 BD4H. This projects replicates paper https://ieeexplore.ieee.org/document/9007352 and combines the various models mentioned in the paper in a Mixture of Model system and access the impact on model performance."
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "gensim>=4.3.3",
    "ipython>=8.35.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.1",
    "nltk>=3.9.1",
    "numpy==1.26.4",
    "pandas>=1.5.3",
    "pip>=25.0.1",
    "polars>=1.27.0",
    "scikit-learn>=1.6.1",
    "sentence-transformers>=4.0.2",
    "torch>=2.6.0",
    "transformers>=4.51.3",
    "skorch==1.1.0",
    "optuna>=4.3.0",
]
